version: '3.8'

services:
  traefik:
    image: traefik:v2.11.2
    container_name: byteshare-traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.sslresolver.acme.tlschallenge=true
      - --certificatesresolvers.sslresolver.acme.email=${EMAIL}
      - --certificatesresolvers.sslresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=sslresolver"
    networks:
      - byteshare-network
  middleware:
    build:
      context: ./middleware
    image: byteshare-middleware:${BYTESHARE_VERSION}
    container_name: byteshare-middleware
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - WEB_BASE_URL
      - RESEND_API_KEY
      - R2_ACCOUNT_ID
      - R2_ACCESS_KEY
      - R2_SECRET_KEY
      - APPWRITE_URL
      - APPWRITE_PROJECT_ID
      - AWS_APP_REGION
      - AWS_APP_ACCESS_KEY
      - AWS_APP_SECRET_ACCESS_KEY
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`api.localhost`)"
      - "traefik.http.routers.middleware.entrypoints=websecure"
      - "traefik.http.routers.middleware.tls.certresolver=sslresolver"
    networks:
      - byteshare-network
  ui:
    build:
      context: ./ui
    image: byteshare-ui:${BYTESHARE_VERSION}
    container_name: byteshare-ui
    restart: unless-stopped
    depends_on:
      - middleware
      - traefik
    environment:
      - NEXT_PUBLIC_API_BASE_URL
      - NEXT_PUBLIC_APP_URL=${WEB_BASE_URL}
      - NEXT_PUBLIC_APPWRITE_URL=${APPWRITE_URL}
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID
      - NEXT_PUBLIC_API_KEY
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.middleware.rule=Host(`ui.localhost`)"
      - "traefik.http.routers.middleware.entrypoints=websecure"
      - "traefik.http.routers.middleware.tls.certresolver=sslresolver"
    networks:
      - byteshare-network
  
networks:
  byteshare-network:
    driver: bridge