# THIS DOCKER COMPOSE FILE IS FOR DEVELOPMENT PURPOSE ONLY

version: '3.8'

x-logging-config: &logger-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"
      labels: "service={{SERVICE_NAME}}"

services:
  byteshare-middleware:
    build:
      context: ./middleware
    image: byteshare-middleware:${BYTESHARE_VERSION}
    container_name: byteshare-middleware
    <<: *logger-config
    restart: unless-stopped
    environment:
      - WEB_BASE_URL
      - RESEND_API_KEY
      - R2_ACCOUNT_ID
      - R2_ACCESS_KEY
      - R2_SECRET_KEY
      - APPWRITE_URL
      - APPWRITE_PROJECT_ID
      - AWS_APP_REGION
      - AWS_APP_ACCESS_KEY
      - AWS_APP_SECRET_ACCESS_KEY
    ports:
      - 8000:8000
    networks:
      - byteshare-network
  byteshare-ui:
    build:
      context: ./ui
    image: byteshare-ui:${BYTESHARE_VERSION}
    container_name: byteshare-ui
    <<: *logger-config
    restart: unless-stopped
    depends_on:
      - byteshare-middleware
    environment:
      - NEXT_PUBLIC_API_BASE_URL
      - NEXT_PUBLIC_APP_URL=${WEB_BASE_URL}
      - NEXT_PUBLIC_APPWRITE_URL=${APPWRITE_URL}
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID
      - NEXT_PUBLIC_API_KEY
    ports:
      - 3000:3000
    networks:
      - byteshare-network
  # byteshare-cert-manager:
  #   build:
  #     context: ./certificates/manager
  #   image: byteshare-cert-manager:${BYTESHARE_VERSION}
  #   container_name: byteshare-cert-manager
  #   <<: *logger-config
  #   volumes:
  #     - ./certificates:/certificates:rw
  #   environment:
  #     - TRAEFIK_API_URL=http://traefik:8080
  #     - DOMAIN_NAME=localhost
  #   depends_on:
  #     - traefik
  #   networks:
  #     - proxy
  
networks:
  byteshare-network:
    driver: bridge