http:
  routers:
    backend-router:
      rule: "Host(`api.localhost`)"
      service: "byteshare-middleware"
      entryPoints:
        # - http
        - https
      # tls:
      #   domains:
      #     - main: "localhost"
      #       sans:
      #         - "*.localhost"
          # - main: "domain.local"
          #   sans:
          #     - "*.domain.local"
  services:
    byteshare-middleware:
      loadBalancer:
        servers:
          - url: "byteshare-middleware:8000"
# tls:
#   certificates:
#     - certFile: "/etc/certs/localhost.crt"
#       keyFile: "/etc/certs/localhost.pem"