AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  LamdbaLayerName:
    Type: String
    Default: byteshare-dependencies
  R2AccountID:
    Type: String
  R2AccessKey:
    Type: String
  R2SecretKey:
    Type: String
  CorsOrigin:
    Type: String
  ApiKeyValue:
    Type: String

Globals:
  Function:
    Timeout: 900
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,File-Length'"
      AllowOrigin: "'*'"
Resources:
  ByteShareFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: byteshare-api
      MemorySize: 2048
      Handler: main.handler
      Runtime: python3.10
      CodeUri: .
      Layers:
        - Ref: SitePackagesLayer
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          R2_ACCOUNT_ID: !Ref R2AccountID
          R2_ACCESS_KEY: !Ref R2AccessKey
          R2_SECRET_KEY: !Ref R2SecretKey
          WEB_BASE_URL: !Ref CorsOrigin
      Events:
        ApiEventWithProxy:
          Type: Api
          Properties:
            RestApiId:
              Ref: ByteShareAPIGW
            Path: /{proxy+}
            Method: any
  ByteShareAPIGW:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      OpenApiVersion: "3.0.0"
      TracingEnabled: true
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,File-Length'"
        AllowOrigin: !Sub
          - "'${CorsOrigin}'"
          - CorsOrigin: !Ref CorsOrigin
      Auth:
        ApiKeyRequired: true
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties: 
      Name: !Join ["", [{"Ref": "AWS::StackName"}, "-apikey"]]
      Description: "API Key for WebApp"
      Enabled: true
      GenerateDistinctId: false
      Value: !Ref ApiKeyValue
      StageKeys:
        - RestApiId: !Ref ByteShareAPIGW
          StageName: Prod

  SitePackagesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Ref: LamdbaLayerName
      Description: python site packages for byteshare app
      ContentUri: ./python-site-packages.zip
      CompatibleRuntimes:
        - python3.10
      LicenseInfo: "MIT"
      RetentionPolicy: Retain
Outputs:
  ByteShareAPIRes:
    Description: "API Gateway endpoint URL for prod stage of byteshare function"
    Value: !Sub "https://${ByteShareAPIGW}.execute-api.${AWS::Region}.amazonaws.com/prod/"